env:
  browser: true
  es6: true
extends:
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - import
  - jsx-a11y
  - react-hooks
  - react
rules:
  import/newline-after-import:
  - error
  - count: 2
